# Generated by Django 5.0.6 on 2024-06-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsteticaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masaje',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
